name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra
    - name: Build PDF
      run: make LATEXOPT="-interaction nonstopmode -halt-on-error"
    - name: Rename PDF
      run: mv main_spec.pdf openshmem-draft-${{ github.event.pull_request.head.sha }}.pdf
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v1
      with:
        name: openshmem-draft-${{ github.event.pull_request.head.sha }}
        path: openshmem-draft-${{ github.event.pull_request.head.sha }}.pdf
